[package]
name = "termvid"
version = "0.2.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
console = { version = "0.15.5", default-features = false, features = [
  "ansi-parsing",
] }
ctrlc = "3.2.5"
which = "4.4.0"
y4m = "0.7.0"
yansi = "0.5.1"
