[package]
name = "termvid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
console = "0.15.5"
indicatif = "0.17.3"
which = "4.4.0"
tokio = { version = "1.25.0", features = ["full"] }
ffprobe = "0.3.3"

[dependencies.uuid]
version = "1.3.0"
features = ["v4", "fast-rng", "macro-diagnostics"]
